### ISSUE TITLE
I have a question!

### ISSUE THREAD

**Issue by GyoungTaeChae** [amaralibey/OpenVPRLab#1]
Hello 

I really aprreciate your masterpiece, it will help me a lot to understand vpr
reading code , i have question in `model.backbones.dinov2.py`

Line 43,  self.dino.pos_embed.requires_grad_(False)
Line 49, self.out_channels = self.dino.embed_dim

i know what this code does but , in colab, i found there is no attribute in model information .
below is my print output. can you tell me why? 

![Screenshot from 2024-08-01 14-09-53](https://github.com/user-attachments/assets/9f144388-5db4-4a30-ae76-c478c6b35d36)

**Comment by amaralibey** [comment]
Hello @GyoungTaeChae 

Thank you for your interest,

In PyTorch, when you print a model, you'll only see the modules of the model (parameters that are encapsulated in a nn.Module class). You don't see attributes and methods. You will have to look at the source code in order to see everything, which is what I did.

Note: I could have infered `self.out_channels` from the last  `norm` layer. But in DinoV2 the embeding_dim doesn't change and is fixed for all blocks (this is the case for most Transformer  architectures).

**Comment by GyoungTaeChae** [comment]
Thank you so much for your answer!
you taught me a lot!
